app/task/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, HiddenField
from wtforms.validators import DataRequired, Length


class TaskCreateForm(FlaskForm):
    id = HiddenField('ID')
    name = StringField('Название', validators=[DataRequired(), Length(min=1, max=64)])
    start_pos = HiddenField('Начальная позиция',
                            validators=[DataRequired(), Length(min=1, max=128)], default='start')
    end_pos = HiddenField('Конечная позиция', validators=[DataRequired(), Length(min=1, max=128)], default='end')
    submit = SubmitField('Добавить')


class TournamentCreateForm(FlaskForm):
    id = HiddenField('ID')
    name = StringField('Название турнира', validators=[DataRequired(), Length(min=1, max=64)])
    submit = SubmitField('Добавить')

app/task/__init__.py
from flask import Blueprint

bp = Blueprint('task', __name__, static_folder='static')

from app.task import routes

app/task/routes.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_required, current_user

from app import db
from app.models import Task, Tournament, User
from app.task import bp
from app.task.forms import TaskCreateForm, TournamentCreateForm


@bp.route('/tournament/<int:tournament_id>/<int:task_id>', methods=['GET', 'POST'])
@login_required
def task(tournament_id, task_id):
    tournament = Tournament.query.filter_by(id=tournament_id).first()
    if tournament is None:
        flash('Турнир не найден')
        return redirect(url_for('task.tournament_list'))
    task = Task.query.filter_by(id=task_id).first()
    if task is None:
        flash('Задача не найдена')
        return redirect(url_for('task.tournament_list'))

    if request.form.get('end_pos'):
        if task.end_pos == request.form.get('end_pos'):
            flash('Вы решили задачу верно!')
            user = User.query.filter_by(id=current_user.id).first()
            user.score += 1
            db.session.commit()

            length = len(tournament.tasks)
            next_page = url_for('main.rating')
            for i, data in enumerate(tournament.tasks):
                if data.id is task.id:
                    if i < length - 1:
                        next_page = url_for('task.task', tournament_id=tournament.id,
                                            task_id=tournament.tasks[i + 1].id)
                    else:
                        flash('Конец турнира')

            return redirect(next_page)
        else:
            flash('Неправильно решение!')
            return redirect(url_for('task.task', tournament_id=tournament_id, task_id=task_id))

    return render_template('task/task.html', title='Выполняется задание', id=tournament.id, task=task)


@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = TaskCreateForm()
    if form.validate_on_submit():
        task = Task.query.filter_by(name=form.name.data).first()
        if task:
            flash('Такая задача уже существует')
            return redirect(url_for('task.create'))
        task = Task(name=form.name.data, start_pos=form.start_pos.data, end_pos=form.end_pos.data)
        db.session.add(task)
        db.session.commit()
        flash('Задача создана!')
        return redirect(url_for('task.list'))
    return render_template('task/task_create.html', title='Новое задание', form=form)


@bp.route('/list')
@login_required
def list():
    page = request.args.get('page', 1, type=int)
    # Можно добавить поле task.timestamp и сортировать по времени создания задачи
    tasks = Task.query.order_by(Task.name.desc()).paginate(page, 12, False)
    next_url = url_for('task.list', page=tasks.next_num) if tasks.has_next else None
    prev_url = url_for('task.list', page=tasks.prev_num) if tasks.has_prev else None
    return render_template('task/task_list.html', title='Список всех задач', tasks=tasks.items, next_url=next_url,
                           prev_url=prev_url)


@bp.route('/delete/<id>', methods=['GET'])
@login_required
def delete(id):
    task = Task.query.filter_by(id=id).first()
    if task is None:
        flash('Задача не найдена')
        return redirect(url_for('task.list'))
    db.session.delete(task)
    db.session.commit()
    flash('Задача успешно удалена')
    return redirect(url_for('task.list'))


@bp.route('/tournament/create', methods=['GET', 'POST'])
@login_required
def tournament_create():
    form = TournamentCreateForm()
    tasks = Task.query.order_by(Task.name.desc()).all()
    task_list = [(task.name, task.id) for task in tasks]
    if form.validate_on_submit():
        if request.form.get('tasks') is None:
            flash('Выберите хотя бы одно задание')
            return redirect(url_for('task.tournament_create'))
        set = Tournament.query.filter_by(name=form.name.data).first()
        if set:
            flash('Турнир с таким именем уже существует')
            return redirect(url_for('task.tournament_create'))
        tournament = Tournament(name=form.name.data)
        for task_id in request.form.getlist('tasks'):
            task = Task.query.filter_by(id=task_id).first()
            tournament.tasks.append(task)
        db.session.commit()
        flash('Вы создали турнир')
        return redirect(url_for('task.tournament_list'))
    return render_template('task/tournament_create.html', titile='Создать турнир', form=form, list=task_list)


@bp.route('/tournament/list')
@login_required
def tournament_list():
    tournaments = Tournament.query.order_by(Tournament.id.desc()).all()
    return render_template('task/tournament_list.html', title='Выбор игры', tournaments=tournaments)


@bp.route('/tournament/<id>/delete', methods=['GET'])
@login_required
def tournament_delete(id):
    tournament = Tournament.query.filter_by(id=id).first()
    if tournament is None:
        flash('Турнир не найдена')
        return redirect(url_for('task.tournament_list'))
    db.session.delete(tournament)
    db.session.commit()
    flash('Турнир успешно удален')
    return redirect(url_for('task.tournament_list'))

app/templates/task/create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block app_content %}
    <div class="row">
        <div class="col-md-6">
            <h2>Добавить задание</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <h4>Начальная позиция</h4>
            <div id="board_start" style="width: 400px"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-6">
                            <input class="btn btn-danger" type="button" value="Очистить" id="clear_start">
                        </div>
                        <div class="col-md-6">
                            <input class="btn btn-info" type="button" value="Начальная позиция" id="start_start">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <h4>Конечная позиция</h4>
            <div id="board_end" style="width: 400px"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-6">
                            <input class="btn btn-danger" type="button" value="Очистить" id="clear_end">
                        </div>
                        <div class="col-md-6">
                            <input class="btn btn-info" type="button" value="Начальная позиция" id="start_end">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>
    {% for field, errors in form.errors.items() %}
        <div class="alert alert-info">
            {{ form[field].label }}: {{ ', '.join(errors) }}
        </div>
    {% endfor %}

    <form action method="post" class="form" role="form" id="boardForm" name="boardForm">
        {{ form.hidden_tag() }}
        <div class="row">
            <div class="form-group col-md-6">
                {{ form.id }}
                {{ wtf.form_field(form.name, class='form-control') }}
                {{ form.start_pos }}
                {{ form.end_pos }}
                {{ wtf.form_field(form.submit, class='btn btn-primary') }}
            </div>
        </div>
    </form>
{% endblock %}

{% block app_scripts %}
    <script src="{{ url_for('task.static', filename='js/chessboard-1.0.0.js') }}"></script>
    <script>
        $(document).ready(function () {
            let config = {
                draggable: true,
                dropOffBoard: 'trash',
                sparePieces: true
            }
            let board_start = Chessboard('board_start', config)
            let board_end = Chessboard('board_end', config)

            $('#start_start').on('click', board_start.start)
            $('#clear_start').on('click', board_start.clear)

            $('#start_end').on('click', board_end.start)
            $('#clear_end').on('click', board_end.clear)

            document.getElementById('start_pos').value = board_start.fen();
            document.getElementById('end_pos').value = board_end.fen();

            $('#boardForm').submit(function () {
                document.getElementById('start_pos').value = board_start.fen();
                document.getElementById('end_pos').value = board_end.fen();
            });
        });
    </script>
{% endblock %}

{% block app_styles %}
    <link rel="stylesheet" href="{{ url_for('task.static', filename='css/chessboard-1.0.0.css') }}">
{% endblock %}

app/templates/task/task.html
{% extends 'base.html' %}

{% block app_content %}
    <h2>Задача {{ task.name }}</h2>
    <br>
    <div class="row">
        <div class="col-md-2 col-sm-offset-4">
            <div id="board" style="width: 400px"></div>
        </div>
    </div>
    <form action="{{ url_for('task.task', tournament_id=id, task_id=task.id) }}" method="post" class="form" role="form"
          id="boardForm"
          name="boardForm">
        <input type="hidden" id="end_pos" name="end_pos" value="{{ task.start_pos }}">
        <input type="submit" class="btn btn-primary" value="Проверить">
    </form>
{% endblock %}

{% block app_scripts %}
    <script src="{{ url_for('task.static', filename='js/chessboard-1.0.0.js') }}"></script>
    <script>
        $(document).ready(function () {
            let config = {
                draggable: true,
                position: '{{ task.start_pos }}'
            }

            let board = Chessboard('board', config)

            $('#boardForm').submit(function () {
                document.getElementById('end_pos').value = board.fen();
            });
        });
    </script>
{% endblock %}

{% block app_styles %}
    <link rel="stylesheet" href="{{ url_for('task.static', filename='css/chessboard-1.0.0.css') }}">
{% endblock %}

app/templates/task/taskList.html
{% extends "base.html" %}

{% block app_content %}
    <h2>Список всех задач</h2>

    {% for taskrow in tasks | batch(3) %}
        <div class="row">
            {%- for task in taskrow %}
                <div class="col-md-4">
                    <div class="panel panel-primary">
                        <div class="panel-heading clearfix">
                            <h3 class="panel-title pull-left">{{ task.name }}</h3>
                            <a class="btn-sm btn-danger pull-right" href="{{ url_for('task.delete', id=task.id) }}">Удалить</a>
                        </div>
                        <div class="panel-body">
                            <div id="board_{{ task.name }}" class="small-board" style="width: 100%"></div>
                        </div>
                    </div>
                </div>
            {%- endfor %}
        </div>
    {% endfor %}
    <nav>
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> Новые
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %} ">
                <a href="{{ next_url or '#' }}">
                    Старые<span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

{% block app_scripts %}
    <script src="{{ url_for('task.static', filename='js/chessboard-1.0.0.js') }}"></script>

    <script>
        {% for task in tasks %}
            let config_{{ task.name }} = {
                showNotation: false,
                position: '{{ task.start_pos }}'
            }
            let board_{{ task.name }} = Chessboard('board_{{ task.name }}', config_{{ task.name }})
        {% endfor %}
    </script>
{% endblock %}

{% block app_styles %}
    <link rel="stylesheet" href="{{ url_for('task.static', filename='css/chessboard-1.0.0.css') }}">
{% endblock %}

app/templates/task/task_create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block app_content %}
    <div class="row">
        <div class="col-md-6">
            <h2>Добавить задание</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <h4>Начальная позиция</h4>
            <div id="board_start" style="width: 400px"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-6">
                            <input class="btn btn-danger" type="button" value="Очистить" id="clear_start">
                        </div>
                        <div class="col-md-6">
                            <input class="btn btn-info" type="button" value="Начальная позиция" id="start_start">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <h4>Конечная позиция</h4>
            <div id="board_end" style="width: 400px"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-6">
                            <input class="btn btn-danger" type="button" value="Очистить" id="clear_end">
                        </div>
                        <div class="col-md-6">
                            <input class="btn btn-info" type="button" value="Начальная позиция" id="start_end">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <form action method="post" class="form" role="form" id="boardForm" name="boardForm">
        {{ form.hidden_tag() }}
        <div class="row">
            <div class="form-group col-md-6">
                {{ form.id }}
                {{ wtf.form_field(form.name, class='form-control') }}
                {{ form.start_pos }}
                {{ form.end_pos }}
                {{ wtf.form_field(form.submit, class='btn btn-primary') }}
            </div>
        </div>
    </form>
{% endblock %}

{% block app_scripts %}
    <script src="{{ url_for('task.static', filename='js/chessboard-1.0.0.js') }}"></script>
    <script>
        $(document).ready(function () {
            let config = {
                draggable: true,
                dropOffBoard: 'trash',
                sparePieces: true
            }
            let board_start = Chessboard('board_start', config)
            let board_end = Chessboard('board_end', config)

            $('#start_start').on('click', board_start.start)
            $('#clear_start').on('click', board_start.clear)

            $('#start_end').on('click', board_end.start)
            $('#clear_end').on('click', board_end.clear)

            document.getElementById('start_pos').value = board_start.fen();
            document.getElementById('end_pos').value = board_end.fen();

            $('#boardForm').submit(function () {
                document.getElementById('start_pos').value = board_start.fen();
                document.getElementById('end_pos').value = board_end.fen();
            });
        });
    </script>
{% endblock %}

{% block app_styles %}
    <link rel="stylesheet" href="{{ url_for('task.static', filename='css/chessboard-1.0.0.css') }}">
{% endblock %}

app/templates/task/task_list.html
{% extends "base.html" %}

{% block app_content %}
    <h2>Список всех задач</h2>
    {% if tasks %}
        {% for taskrow in tasks | batch(3) %}
            <div class="row">
                {%- for task in taskrow %}
                    <div class="col-md-4">
                        <div class="panel panel-primary">
                            <div class="panel-heading clearfix">
                                <h3 class="panel-title pull-left">{{ task.name }}</h3>
                                <a class="btn btn-sm btn-danger pull-right" href="{{ url_for('task.delete', id=task.id) }}">Удалить</a>
                            </div>
                            <div class="panel-body">
                                <div id="board_{{ task.name }}" class="small-board" style="width: 100%"></div>
                            </div>
                        </div>
                    </div>
                {%- endfor %}
            </div>
        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous{% if not prev_url %} disabled{% endif %}">
                    <a href="{{ prev_url or '#' }}">
                        <span aria-hidden="true">&larr;</span> Новые
                    </a>
                </li>
                <li class="next{% if not next_url %} disabled{% endif %} ">
                    <a href="{{ next_url or '#' }}">
                        Старые<span aria-hidden="true">&rarr;</span>
                    </a>
                </li>
            </ul>
        </nav>
    {% else %}
        <h4>Ещё не создано ни одной задачи :(</h4>
        <a href="{{ url_for('task.create') }}" class="btn btn-primary">Создать сейчас!</a>
    {% endif %}
{% endblock %}

{% block app_scripts %}
    <script src="{{ url_for('task.static', filename='js/chessboard-1.0.0.js') }}"></script>

    <script>
        {% for task in tasks %}
            let config_{{ task.name }} = {
                showNotation: false,
                position: '{{ task.start_pos }}'
            }
            let board_{{ task.name }} = Chessboard('board_{{ task.name }}', config_{{ task.name }})
        {% endfor %}
    </script>
{% endblock %}

{% block app_styles %}
    <link rel="stylesheet" href="{{ url_for('task.static', filename='css/chessboard-1.0.0.css') }}">
{% endblock %}

app/templates/task/tournament_create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block app_content %}
    <h2>Добавить турнир</h2>
    {% if list %}
        <form action="{{ url_for('task.tournament_create') }}" method="post" class="form" role="form">
            {{ form.hidden_tag() }}
            {{ form.id }}
            {{ wtf.form_field(form.name) }}
            {% if list %}
                <h4>Выберите задания:</h4>
                {% for task in list %}
                    <div class="form-check">
                        <label>
                            <input type="checkbox" name="tasks" value="{{ task[1] }}"> <span
                                class="label-text">{{ task[0] }}</span>
                        </label>
                    </div>
                {% endfor %}
            {% endif %}
            {{ wtf.form_field(form.submit, class='btn btn-primary') }}
        </form>
    {% else %}
        <h4>Нельзя создать турнир кода нету ни одной задачи :(</h4>
        <a href="{{ url_for('task.create') }}" class="btn btn-primary">Создать задачу</a>
    {% endif %}
{% endblock %}

app/templates/task/tournament_list.html
{% extends "base.html" %}

{% block app_content %}
    <h2>Список турниров</h2>
    {% if tournaments %}
        {% for tournaments_batch in tournaments | batch(4) %}
            <div class="row">
                {% for tournament in tournaments_batch %}
                    <div class="col-md-3">
                        <div class="panel panel-primary">
                            <div class="panel-heading clearfix">
                                <h3 class="panel-title pull-left">{{ tournament.name }}</h3>
                                <a class="btn btn-sm btn-danger pull-right"
                                   href="{{ url_for('task.tournament_delete', id=tournament.id) }}">Удалить</a>
                            </div>
                            <div class="panel-body">
                                Колличество задач: {{ tournament.tasks|length }}
                            </div>
                            <div class="panel-footer clearfix">
                                <a href="{{ url_for('task.task', tournament_id=tournament.id, task_id=tournament.tasks[0].id) }}"
                                   class="btn btn-sm btn-default pull-right">Запустить</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        <h4>Турниров нету, играть не во что :(</h4>
        <a href="{{ url_for('task.tournament_create') }}" class="btn btn-primary">Создать турнир</a>
    {% endif %}
{% endblock %}